name: Auto Deploy to EC2 (Staging)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Frappe to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
	  script: |
		  set -e
		  cd /home/ec2-user/frappe_docker
		  git pull origin staging
		  docker-compose -f pwd.yml pull
		  docker-compose -f pwd.yml up -d

